services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: 'cloud_storage'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: