services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - app-network
    restart: always
    environment:
      POSTGRES_DB: 'cloud_storage'
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
    ports:
      - '5555:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: 'cloud_storage_test'
      POSTGRES_USER: 'test_user'
      POSTGRES_PASSWORD: 'test_password'
    ports:
      - '5556:5432'
    volumes:
      - postgres_data_test:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - app-network
    restart: always
    environment:
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    command: server ~/minio --console-address :9090
    ports:
      - '9090:9090'
      - '9000:9000'
    volumes:
      - minio_data:/minio

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data


networks:
  app-network:
    driver: bridge


volumes:
  postgres_data:
  postgres_data_test:
  minio_data:
  redis_data: